import { ArrowRight, BadgeCheck, BarChart3, Check, CircleDollarSign, Globe2, Handshake, LockKeyhole, Search, ShieldCheck, Users, Zap } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

export function TrustStrip(){return <section className="border-b border-border bg-white"><div className="container-x grid grid-cols-2 divide-x divide-border sm:grid-cols-4"><div className="p-7 text-center"><b className="block text-2xl">190+</b><span className="text-xs text-muted-foreground">countries reachable</span></div><div className="p-7 text-center"><b className="block text-2xl">1,200+</b><span className="text-xs text-muted-foreground">channels listed</span></div><div className="p-7 text-center"><b className="block text-2xl">24/7</b><span className="text-xs text-muted-foreground">global marketplace</span></div><div className="p-7 text-center"><b className="block text-2xl">Clear</b><span className="text-xs text-muted-foreground">deal milestones</span></div></div></section>}

export function DarkFeature(){return <section id="how" className="bg-[#111a27] py-24 text-white"><div className="container-x"><div className="grid gap-14 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ffcf4a]">A cleaner deal flow</p><h2 className="display mt-4 text-5xl font-black sm:text-6xl">From “I’m interested” to ownership.</h2><p className="mt-6 max-w-lg leading-7 text-white/65">TubeX turns a messy private transaction into clear stages so both sides know what happens next.</p><Button asChild variant="accent" className="mt-8"><Link href="/#sell">See the selling flow <ArrowRight size={16}/></Link></Button></div><div className="grid gap-5 sm:grid-cols-2">{[{icon:Search,title:"Discover",text:"Filter by niche, audience, geography, revenue signals and asking price."},{icon:BarChart3,title:"Verify",text:"Review structured listing information before starting a conversation."},{icon:Handshake,title:"Agree",text:"Move through offer and counter-offer steps with a clear record."},{icon:LockKeyhole,title:"Transfer",text:"Keep ownership-transfer milestones visible until the deal is complete."}].map(({icon:Icon,title,text})=><div key={title} className="rounded-3xl border border-white/10 bg-white/[.04] p-7"><Icon className="text-[#ffcf4a]" size={23}/><h3 className="mt-7 text-xl font-bold">{title}</h3><p className="mt-3 leading-6 text-white/60">{text}</p></div>)}</div></div></div></section>}

export function SellerBuyer(){return <section id="sell" className="py-24"><div className="container-x grid gap-6 lg:grid-cols-2"><div className="rounded-[32px] bg-[#e9e7ff] p-9 sm:p-12"><div className="flex size-12 items-center justify-center rounded-2xl bg-white"><CircleDollarSign/></div><h2 className="display mt-8 text-4xl font-black">Turn your channel into a transferable asset.</h2><p className="mt-5 leading-7 text-muted-foreground">Create a structured listing, show the numbers buyers actually need, and manage interest without juggling scattered spreadsheets and DMs.</p><ul className="mt-8 space-y-3 text-sm font-medium">{["Guided listing setup","Performance-focused fields","Buyer inquiry management","Clear deal milestones"].map(x=><li key={x} className="flex gap-3"><Check size={18}/>{x}</li>)}</ul><Button className="mt-9" asChild><Link href="/seller-dashboard">Start a listing <ArrowRight size={16}/></Link></Button></div><div className="rounded-[32px] bg-[#eaf5ed] p-9 sm:p-12"><div className="flex size-12 items-center justify-center rounded-2xl bg-white"><Globe2/></div><h2 className="display mt-8 text-4xl font-black">Buy across borders with more context.</h2><p className="mt-5 leading-7 text-muted-foreground">Compare channels from different markets in one place. Review niche, audience, growth and listing details before you make an offer.</p><ul className="mt-8 space-y-3 text-sm font-medium">{["Global channel discovery","Comparable listing data","Direct buyer questions","Transparent offer history"].map(x=><li key={x} className="flex gap-3"><Check size={18}/>{x}</li>)}</ul><Button className="mt-9" variant="outline" asChild><Link href="/explore-channels">Explore opportunities <ArrowRight size={16}/></Link></Button></div></div></section>}

export function Safety(){return <section id="safety" className="border-y border-border bg-white py-24"><div className="container-x grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#7c5cff]">Built around trust</p><h2 className="display mt-4 text-5xl font-black">Less guessing. More evidence.</h2></div><div className="grid gap-4 sm:grid-cols-2">{[{icon:ShieldCheck,t:"Structured verification",d:"Separate listing claims from fields that can be reviewed or supported."},{icon:Users,t:"Two-sided workflow",d:"Buyers and sellers get milestones rather than an endless DM thread."},{icon:Zap,t:"Fast discovery",d:"Search and compare the information that matters to your purchase."},{icon:LockKeyhole,t:"Security first",d:"Authentication, validation, rate limits and server-side authorization belong in the backend."}].map(({icon:Icon,t,d})=><Card key={t} className="p-7"><Icon size={22}/><h3 className="mt-5 font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{d}</p></Card>)}</div></div></section>}

export function CTA(){return <section className="py-24"><div className="container-x overflow-hidden rounded-[36px] bg-[#111a27] p-9 text-white sm:p-14"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ffcf4a]">Your next channel deal starts here</p><h2 className="display mt-4 text-5xl font-black sm:text-6xl">Build a marketplace where the deal makes sense before the money moves.</h2><p className="mt-6 max-w-2xl text-white/60">Browse channels, create a listing, or connect the backend to your real marketplace workflow when you are ready.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild variant="accent" size="lg"><Link href="/explore-channels">Browse channels</Link></Button><Button asChild variant="outline" size="lg" className="border-white/20 bg-white/5 text-white hover:bg-white/10"><Link href="/seller-dashboard">Sell on TubeX</Link></Button></div></div></div></section>}

export function Footer(){return <footer className="border-t border-border bg-white"><div className="container-x grid gap-10 py-14 md:grid-cols-[1.4fr_1fr_1fr_1fr]"><div><div className="font-black text-xl">TubeX</div><p className="mt-4 max-w-sm text-sm leading-6 text-muted-foreground">A global marketplace concept for discovering, buying and selling YouTube channels with a structured deal experience.</p></div>
<div><h3 className="text-sm font-bold">Marketplace</h3><div className="mt-4 space-y-3 text-sm text-muted-foreground"><Link href="/explore-channels" className="block hover:text-foreground">Browse channels</Link><Link href="/seller-dashboard" className="block hover:text-foreground">Sell a channel</Link><Link href="/#how" className="block hover:text-foreground">How it works</Link></div></div>
<div><h3 className="text-sm font-bold">Company</h3><div className="mt-4 space-y-3 text-sm text-muted-foreground"><span className="block">About</span><Link href="/#safety" className="block hover:text-foreground">Safety</Link><span className="block">Contact</span></div></div>
<div><h3 className="text-sm font-bold">Legal</h3><div className="mt-4 space-y-3 text-sm text-muted-foreground"><span className="block">Privacy</span><span className="block">Terms</span><span className="block">Cookies</span></div></div>
</div><div className="container-x flex flex-col gap-3 border-t py-6 text-xs text-muted-foreground sm:flex-row sm:justify-between"><span>© 2026 TubeX. All rights reserved.</span><span>Built for a global creator economy.</span></div></footer>}
